// Mocks generated by Mockito 5.4.4 from annotations
// in sprout_inventory/test/features/product/domain/repository/product_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sprout_inventory/core/error/failure.dart' as _i6;
import 'package:sprout_inventory/features/product/domain/entities/product_detail.dart'
    as _i7;
import 'package:sprout_inventory/features/product/domain/entities/products.dart'
    as _i5;
import 'package:sprout_inventory/features/product/domain/repository/product_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProductRepository extends _i1.Mock
    implements _i3.IProductRepository {
  @override
  _i4.Future<_i2.Either<_i5.Products, _i6.Failure>> getProducts(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [page],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Products, _i6.Failure>>.value(
            _FakeEither_0<_i5.Products, _i6.Failure>(
          this,
          Invocation.method(
            #getProducts,
            [page],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Products, _i6.Failure>>.value(
                _FakeEither_0<_i5.Products, _i6.Failure>(
          this,
          Invocation.method(
            #getProducts,
            [page],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Products, _i6.Failure>>);

  @override
  _i4.Future<_i2.Either<_i7.ProductDetail, _i6.Failure>> getProductDetail(
          int? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductDetail,
          [productId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.ProductDetail, _i6.Failure>>.value(
                _FakeEither_0<_i7.ProductDetail, _i6.Failure>(
          this,
          Invocation.method(
            #getProductDetail,
            [productId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i7.ProductDetail, _i6.Failure>>.value(
                _FakeEither_0<_i7.ProductDetail, _i6.Failure>(
          this,
          Invocation.method(
            #getProductDetail,
            [productId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.ProductDetail, _i6.Failure>>);
}
