// Mocks generated by Mockito 5.4.4 from annotations
// in sprout_inventory/test/core/utils/network_info/network_info_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sprout_inventory/core/utils/network_info.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [INetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockINetworkInfo extends _i1.Mock implements _i2.INetworkInfo {
  @override
  _i3.Future<bool> get isNetworkConnected => (super.noSuchMethod(
        Invocation.getter(#isNetworkConnected),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Stream<_i4.InternetConnectionStatus> get onStatusChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onStatusChanged),
        returnValue: _i3.Stream<_i4.InternetConnectionStatus>.empty(),
        returnValueForMissingStub:
            _i3.Stream<_i4.InternetConnectionStatus>.empty(),
      ) as _i3.Stream<_i4.InternetConnectionStatus>);
}
